// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxffkawfnjlltqnhekvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4ZmZrYXdmbmpsbHRxbmhla3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTc2OTcsImV4cCI6MjA2NDY5MzY5N30.i6qewG644fiBDDBkXb3NQKjU4KWF0S24gYOh6hzi8Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);